---
- name: Init servers
  hosts: servers
  strategy: free
  remote_user: pi
  become: true

  tasks:
  - name: Run apt-get Update
    apt: 
      upgrade: yes
      update_cache: yes
    register: apt_status

  - name: Install usefull packages
    apt: 
      pkg: 
        - vim
        - telnet
        - iputils-ping

  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  # Python 2.7.x version cli returns the output to stderr thus all outputs are redirected to stdout
  - name: Get default Python version
    shell: |
      python --version 2>&1 
    register: python_version

  - name: Select Python3.x as default
    shell: |
      update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    when: python_version.stdout.find('2.7') != -1

  - name: Add entries to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
      state: present
    loop: "{{ play_hosts }}"

  - name: Check is cgroup enabled?
    shell: |
      cat /boot/firmware/cmdline.txt || echo "missing"
    register: cmdline_file

  - name: Enable cgroup 
    lineinfile:
      path: /boot/firmware/cmdline.txt
      line: cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
      insertbefore: BOF
      create: yes
    when: cmdline_file.stdout.find('cgroup') == -1
    register: cmdline_status

  - name: Reboot servers due to cmdline changes
    reboot:
      reboot_timeout: 90
    when: 
      - cmdline_status.changed
