---
- name: Install k3s on master server
  hosts: master
  remote_user: pi
  become: true

  tasks:

  - name: Check is k3s installed
    shell: |
      systemctl status k3s 2>&1; exit 0
    register: k3s_service_status

  - name: Install k3s on master server
    shell: |
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--no-deploy servicelb" sh -s -
    when: k3s_service_status.stdout.find('running') == -1

  - name: Export k3s.yaml to use kubectl from remote machine
    run_once: yes
    fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: /workdir/k3s-config/.kubeconfig
      flat: yes
    when: "inventory_hostname == 'rp-000'"