---
- name: Install k3s on master server
  hosts: master
  remote_user: pi
  become: true

  tasks:

  - name: Check is k3s installed
    shell: |
      systemctl status k3s 2>&1; exit 0
    register: k3s_service_status

  - name: Install k3s on master server
    shell: |
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--no-deploy servicelb" sh -s -
    when: k3s_service_status.stdout.find('running') == -1